name: Build


on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential pkg-config

      - name: Install X11 and OpenCV development libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libx11-dev libxrandr-dev

      - name: Install CMake
        run: |
          curl -LO https://github.com/Kitware/CMake/releases/download/v4.1.2/cmake-4.1.2-linux-x86_64.sh
          chmod +x cmake-4.1.2-linux-x86_64.sh
          sudo ./cmake-4.1.2-linux-x86_64.sh --skip-license --prefix=/usr/local
          cmake --version

      - name: Configure
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build --config Release -- -j$(nproc)
